//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MSharpen.rc
//
#define _USE_DECLSPECS_FOR_SAL          0
#define _USE_ATTRIBUTES_FOR_SAL         0
#define __drv_typeConst                 0
#define _HAS_CXX17                      0
#define _HAS_CXX20                      0
#define _CRT_FUNCTIONS_REQUIRED         0
#define _CRT_HAS_CXX17                  0
#define PASSIVE_LEVEL                   0
#define PRAGMA_DEPRECATED_DDK           0
#define ERROR_SEVERITY_SUCCESS          0x00000000
#define FALSE                           0
#define _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES 0
#define _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_COUNT 0
#define _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES 0
#define _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_MEMORY 0
#define _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES_MEMORY 0
#define EXCEPTION_CONTINUE_SEARCH       0
#define PRODUCT_UNDEFINED               0x00000000
#define LANG_NEUTRAL                    0x00
#define SUBLANG_NEUTRAL                 0x00
#define SORT_DEFAULT                    0x0
#define SORT_JAPANESE_XJIS              0x0
#define SORT_CHINESE_BIG5               0x0
#define SORT_CHINESE_PRCP               0x0
#define SORT_KOREAN_KSC                 0x0
#define SORT_HUNGARIAN_DEFAULT          0x0
#define SORT_GEORGIAN_TRADITIONAL       0x0
#define __drv_typeCond                  1
#define VS_VERSION_INFO                 1
#define VFFF_ISSHAREDFILE               0x0001
#define VFF_CURNEDEST                   0x0001
#define VIFF_FORCEINSTALL               0x0001
#define _HAS_EXCEPTIONS                 1
#define _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE 1
#define _CRT_BUILD_DESKTOP_APP          1
#define _CRT_INTERNAL_NONSTDC_NAMES     1
#define __STDC_WANT_SECURE_LIB__        1
#define _UPPER                          0x01
#define ANYSIZE_ARRAY                   1
#define APC_LEVEL                       1
#define STRICT                          1
#define TRUE                            1
#define EPERM                           1
#define EXCEPTION_EXECUTE_HANDLER       1
#define VER_SUITE_SMALLBUSINESS         0x00000001
#define PRODUCT_ULTIMATE                0x00000001
#define LANG_ARABIC                     0x01
#define SUBLANG_DEFAULT                 0x01
#define SUBLANG_AFRIKAANS_SOUTH_AFRICA  0x01
#define SUBLANG_ALBANIAN_ALBANIA        0x01
#define SUBLANG_ALSATIAN_FRANCE         0x01
#define SUBLANG_AMHARIC_ETHIOPIA        0x01
#define SUBLANG_ARABIC_SAUDI_ARABIA     0x01
#define SUBLANG_ARMENIAN_ARMENIA        0x01
#define SUBLANG_ASSAMESE_INDIA          0x01
#define SUBLANG_AZERI_LATIN             0x01
#define SUBLANG_AZERBAIJANI_AZERBAIJAN_LATIN 0x01
#define SUBLANG_BANGLA_INDIA            0x01
#define SUBLANG_BASHKIR_RUSSIA          0x01
#define SUBLANG_BASQUE_BASQUE           0x01
#define SUBLANG_BELARUSIAN_BELARUS      0x01
#define SUBLANG_BENGALI_INDIA           0x01
#define SUBLANG_BRETON_FRANCE           0x01
#define SUBLANG_BULGARIAN_BULGARIA      0x01
#define SUBLANG_CATALAN_CATALAN         0x01
#define SUBLANG_CENTRAL_KURDISH_IRAQ    0x01
#define SUBLANG_CHEROKEE_CHEROKEE       0x01
#define SUBLANG_CHINESE_TRADITIONAL     0x01
#define SUBLANG_CORSICAN_FRANCE         0x01
#define SUBLANG_CZECH_CZECH_REPUBLIC    0x01
#define SUBLANG_CROATIAN_CROATIA        0x01
#define SUBLANG_DANISH_DENMARK          0x01
#define SUBLANG_DARI_AFGHANISTAN        0x01
#define SUBLANG_DIVEHI_MALDIVES         0x01
#define SUBLANG_DUTCH                   0x01
#define SUBLANG_ENGLISH_US              0x01
#define SUBLANG_ESTONIAN_ESTONIA        0x01
#define SUBLANG_FAEROESE_FAROE_ISLANDS  0x01
#define SUBLANG_FILIPINO_PHILIPPINES    0x01
#define SUBLANG_FINNISH_FINLAND         0x01
#define SUBLANG_FRENCH                  0x01
#define SUBLANG_FRISIAN_NETHERLANDS     0x01
#define SUBLANG_GALICIAN_GALICIAN       0x01
#define SUBLANG_GEORGIAN_GEORGIA        0x01
#define SUBLANG_GERMAN                  0x01
#define SUBLANG_GREEK_GREECE            0x01
#define SUBLANG_GREENLANDIC_GREENLAND   0x01
#define SUBLANG_GUJARATI_INDIA          0x01
#define SUBLANG_HAUSA_NIGERIA_LATIN     0x01
#define SUBLANG_HAWAIIAN_US             0x01
#define SUBLANG_HEBREW_ISRAEL           0x01
#define SUBLANG_HINDI_INDIA             0x01
#define SUBLANG_HUNGARIAN_HUNGARY       0x01
#define SUBLANG_ICELANDIC_ICELAND       0x01
#define SUBLANG_IGBO_NIGERIA            0x01
#define SUBLANG_INDONESIAN_INDONESIA    0x01
#define SUBLANG_INUKTITUT_CANADA        0x01
#define SUBLANG_ITALIAN                 0x01
#define SUBLANG_JAPANESE_JAPAN          0x01
#define SUBLANG_KANNADA_INDIA           0x01
#define SUBLANG_KAZAK_KAZAKHSTAN        0x01
#define SUBLANG_KHMER_CAMBODIA          0x01
#define SUBLANG_KICHE_GUATEMALA         0x01
#define SUBLANG_KINYARWANDA_RWANDA      0x01
#define SUBLANG_KONKANI_INDIA           0x01
#define SUBLANG_KOREAN                  0x01
#define SUBLANG_KYRGYZ_KYRGYZSTAN       0x01
#define SUBLANG_LAO_LAO                 0x01
#define SUBLANG_LATVIAN_LATVIA          0x01
#define SUBLANG_LITHUANIAN              0x01
#define SUBLANG_LUXEMBOURGISH_LUXEMBOURG 0x01
#define SUBLANG_MACEDONIAN_MACEDONIA    0x01
#define SUBLANG_MALAY_MALAYSIA          0x01
#define SUBLANG_MALAYALAM_INDIA         0x01
#define SUBLANG_MALTESE_MALTA           0x01
#define SUBLANG_MAORI_NEW_ZEALAND       0x01
#define SUBLANG_MAPUDUNGUN_CHILE        0x01
#define SUBLANG_MARATHI_INDIA           0x01
#define SUBLANG_MOHAWK_MOHAWK           0x01
#define SUBLANG_MONGOLIAN_CYRILLIC_MONGOLIA 0x01
#define SUBLANG_NEPALI_NEPAL            0x01
#define SUBLANG_NORWEGIAN_BOKMAL        0x01
#define SUBLANG_OCCITAN_FRANCE          0x01
#define SUBLANG_ODIA_INDIA              0x01
#define SUBLANG_ORIYA_INDIA             0x01
#define SUBLANG_PASHTO_AFGHANISTAN      0x01
#define SUBLANG_PERSIAN_IRAN            0x01
#define SUBLANG_POLISH_POLAND           0x01
#define SUBLANG_PORTUGUESE_BRAZILIAN    0x01
#define SUBLANG_PUNJABI_INDIA           0x01
#define SUBLANG_QUECHUA_BOLIVIA         0x01
#define SUBLANG_ROMANIAN_ROMANIA        0x01
#define SUBLANG_ROMANSH_SWITZERLAND     0x01
#define SUBLANG_RUSSIAN_RUSSIA          0x01
#define SUBLANG_SAKHA_RUSSIA            0x01
#define SUBLANG_SAMI_NORTHERN_NORWAY    0x01
#define SUBLANG_SANSKRIT_INDIA          0x01
#define SUBLANG_SCOTTISH_GAELIC         0x01
#define SUBLANG_SERBIAN_CROATIA         0x01
#define SUBLANG_SINDHI_INDIA            0x01
#define SUBLANG_SINHALESE_SRI_LANKA     0x01
#define SUBLANG_SOTHO_NORTHERN_SOUTH_AFRICA 0x01
#define SUBLANG_SLOVAK_SLOVAKIA         0x01
#define SUBLANG_SLOVENIAN_SLOVENIA      0x01
#define SUBLANG_SPANISH                 0x01
#define SUBLANG_SWAHILI_KENYA           0x01
#define SUBLANG_SWEDISH                 0x01
#define SUBLANG_SYRIAC_SYRIA            0x01
#define SUBLANG_TAJIK_TAJIKISTAN        0x01
#define SUBLANG_TAMIL_INDIA             0x01
#define SUBLANG_TATAR_RUSSIA            0x01
#define SUBLANG_TELUGU_INDIA            0x01
#define SUBLANG_THAI_THAILAND           0x01
#define SUBLANG_TIBETAN_PRC             0x01
#define SUBLANG_TIGRINYA_ETHIOPIA       0x01
#define SUBLANG_TSWANA_SOUTH_AFRICA     0x01
#define SUBLANG_TURKISH_TURKEY          0x01
#define SUBLANG_TURKMEN_TURKMENISTAN    0x01
#define SUBLANG_UIGHUR_PRC              0x01
#define SUBLANG_UKRAINIAN_UKRAINE       0x01
#define SUBLANG_UPPER_SORBIAN_GERMANY   0x01
#define SUBLANG_URDU_PAKISTAN           0x01
#define SUBLANG_UZBEK_LATIN             0x01
#define SUBLANG_VIETNAMESE_VIETNAM      0x01
#define SUBLANG_WELSH_UNITED_KINGDOM    0x01
#define SUBLANG_WOLOF_SENEGAL           0x01
#define SUBLANG_XHOSA_SOUTH_AFRICA      0x01
#define SUBLANG_YAKUT_RUSSIA            0x01
#define SUBLANG_YI_PRC                  0x01
#define SUBLANG_YORUBA_NIGERIA          0x01
#define SUBLANG_ZULU_SOUTH_AFRICA       0x01
#define SORT_INVARIANT_MATH             0x1
#define SORT_JAPANESE_UNICODE           0x1
#define SORT_CHINESE_UNICODE            0x1
#define SORT_KOREAN_UNICODE             0x1
#define SORT_GERMAN_PHONE_BOOK          0x1
#define SORT_HUNGARIAN_TECHNICAL        0x1
#define SORT_GEORGIAN_MODERN            0x1
#define WINAPI_FAMILY_PC_APP            2
#define __drv_typeBitset                2
#define VFF_FILEINUSE                   0x0002
#define VIFF_DONTDELETEOLD              0x0002
#define _LOWER                          0x02
#define DISPATCH_LEVEL                  2
#define ENOENT                          2
#define VER_SUITE_ENTERPRISE            0x00000002
#define PRODUCT_HOME_BASIC              0x00000002
#define LANG_BULGARIAN                  0x02
#define SUBLANG_SYS_DEFAULT             0x02
#define SUBLANG_ARABIC_IRAQ             0x02
#define SUBLANG_AZERI_CYRILLIC          0x02
#define SUBLANG_AZERBAIJANI_AZERBAIJAN_CYRILLIC 0x02
#define SUBLANG_BANGLA_BANGLADESH       0x02
#define SUBLANG_BENGALI_BANGLADESH      0x02
#define SUBLANG_CHINESE_SIMPLIFIED      0x02
#define SUBLANG_DUTCH_BELGIAN           0x02
#define SUBLANG_ENGLISH_UK              0x02
#define SUBLANG_FRENCH_BELGIAN          0x02
#define SUBLANG_FULAH_SENEGAL           0x02
#define SUBLANG_GERMAN_SWISS            0x02
#define SUBLANG_INUKTITUT_CANADA_LATIN  0x02
#define SUBLANG_IRISH_IRELAND           0x02
#define SUBLANG_ITALIAN_SWISS           0x02
#define SUBLANG_KASHMIRI_SASIA          0x02
#define SUBLANG_KASHMIRI_INDIA          0x02
#define SUBLANG_LOWER_SORBIAN_GERMANY   0x02
#define SUBLANG_MALAY_BRUNEI_DARUSSALAM 0x02
#define SUBLANG_MONGOLIAN_PRC           0x02
#define SUBLANG_NEPALI_INDIA            0x02
#define SUBLANG_NORWEGIAN_NYNORSK       0x02
#define SUBLANG_PORTUGUESE              0x02
#define SUBLANG_PULAR_SENEGAL           0x02
#define SUBLANG_PUNJABI_PAKISTAN        0x02
#define SUBLANG_QUECHUA_ECUADOR         0x02
#define SUBLANG_SAMI_NORTHERN_SWEDEN    0x02
#define SUBLANG_SERBIAN_LATIN           0x02
#define SUBLANG_SINDHI_PAKISTAN         0x02
#define SUBLANG_SINDHI_AFGHANISTAN      0x02
#define SUBLANG_SPANISH_MEXICAN         0x02
#define SUBLANG_SWEDISH_FINLAND         0x02
#define SUBLANG_TAMAZIGHT_ALGERIA_LATIN 0x02
#define SUBLANG_TAMIL_SRI_LANKA         0x02
#define SUBLANG_TIGRIGNA_ERITREA        0x02
#define SUBLANG_TIGRINYA_ERITREA        0x02
#define SUBLANG_TSWANA_BOTSWANA         0x02
#define SUBLANG_URDU_INDIA              0x02
#define SUBLANG_UZBEK_CYRILLIC          0x02
#define SUBLANG_VALENCIAN_VALENCIA      0x02
#define SORT_CHINESE_PRC                0x2
#define WINAPI_FAMILY_PHONE_APP         3
#define __drv_typeExpr                  3
#define RTL_BALANCED_NODE_RESERVED_PARENT_MASK 3
#define ESRCH                           3
#define PRODUCT_HOME_PREMIUM            0x00000003
#define LANG_CATALAN                    0x03
#define LANG_VALENCIAN                  0x03
#define SUBLANG_CUSTOM_DEFAULT          0x03
#define SUBLANG_ARABIC_EGYPT            0x03
#define SUBLANG_CHINESE_HONGKONG        0x03
#define SUBLANG_ENGLISH_AUS             0x03
#define SUBLANG_FRENCH_CANADIAN         0x03
#define SUBLANG_GERMAN_AUSTRIAN         0x03
#define SUBLANG_QUECHUA_PERU            0x03
#define SUBLANG_SAMI_NORTHERN_FINLAND   0x03
#define SUBLANG_SERBIAN_CYRILLIC        0x03
#define SUBLANG_SPANISH_MODERN          0x03
#define SORT_CHINESE_BOPOMOFO           0x3
#define WINAPI_FAMILY_SYSTEM            4
#define VFF_BUFFTOOSMALL                0x0004
#define _DIGIT                          0x04
#define EINTR                           4
#define VER_SUITE_BACKOFFICE            0x00000004
#define PRODUCT_ENTERPRISE              0x00000004
#define LANG_CHINESE                    0x04
#define LANG_CHINESE_SIMPLIFIED         0x04
#define SUBLANG_CUSTOM_UNSPECIFIED      0x04
#define SUBLANG_ARABIC_LIBYA            0x04
#define SUBLANG_CHINESE_SINGAPORE       0x04
#define SUBLANG_CROATIAN_BOSNIA_HERZEGOVINA_LATIN 0x04
#define SUBLANG_ENGLISH_CAN             0x04
#define SUBLANG_FRENCH_SWISS            0x04
#define SUBLANG_GERMAN_LUXEMBOURG       0x04
#define SUBLANG_SAMI_LULE_NORWAY        0x04
#define SUBLANG_SPANISH_GUATEMALA       0x04
#define SUBLANG_TAMAZIGHT_MOROCCO_TIFINAGH 0x04
#define SORT_JAPANESE_RADICALSTROKE     0x4
#define SORT_CHINESE_RADICALSTROKE      0x4
#define WINAPI_FAMILY_SERVER            5
#define EIO                             5
#define PRODUCT_HOME_BASIC_N            0x00000005
#define LANG_CZECH                      0x05
#define SUBLANG_UI_CUSTOM_DEFAULT       0x05
#define SUBLANG_ARABIC_ALGERIA          0x05
#define SUBLANG_BOSNIAN_BOSNIA_HERZEGOVINA_LATIN 0x05
#define SUBLANG_CHINESE_MACAU           0x05
#define SUBLANG_ENGLISH_NZ              0x05
#define SUBLANG_FRENCH_LUXEMBOURG       0x05
#define SUBLANG_GERMAN_LIECHTENSTEIN    0x05
#define SUBLANG_SAMI_LULE_SWEDEN        0x05
#define SUBLANG_SPANISH_COSTA_RICA      0x05
#define WINAPI_FAMILY_GAMES             6
#define ENXIO                           6
#define PRODUCT_BUSINESS                0x00000006
#define LANG_DANISH                     0x06
#define SUBLANG_ARABIC_MOROCCO          0x06
#define SUBLANG_ENGLISH_EIRE            0x06
#define SUBLANG_FRENCH_MONACO           0x06
#define SUBLANG_SAMI_SOUTHERN_NORWAY    0x06
#define SUBLANG_SERBIAN_BOSNIA_HERZEGOVINA_LATIN 0x06
#define SUBLANG_SPANISH_PANAMA          0x06
#define E2BIG                           7
#define PRODUCT_STANDARD_SERVER         0x00000007
#define LANG_GERMAN                     0x07
#define SUBLANG_ARABIC_TUNISIA          0x07
#define SUBLANG_ENGLISH_SOUTH_AFRICA    0x07
#define SUBLANG_SAMI_SOUTHERN_SWEDEN    0x07
#define SUBLANG_SERBIAN_BOSNIA_HERZEGOVINA_CYRILLIC 0x07
#define SUBLANG_SPANISH_DOMINICAN_REPUBLIC 0x07
#define _CRT_PACKING                    8
#define _SPACE                          0x08
#define MEMORY_ALLOCATION_ALIGNMENT     8
#define ENOEXEC                         8
#define VER_SUITE_COMMUNICATIONS        0x00000008
#define PRODUCT_DATACENTER_SERVER       0x00000008
#define LANG_GREEK                      0x08
#define SUBLANG_ARABIC_OMAN             0x08
#define SUBLANG_BOSNIAN_BOSNIA_HERZEGOVINA_CYRILLIC 0x08
#define SUBLANG_ENGLISH_JAMAICA         0x08
#define SUBLANG_SAMI_SKOLT_FINLAND      0x08
#define SUBLANG_SPANISH_VENEZUELA       0x08
#define EBADF                           9
#define PRODUCT_SMALLBUSINESS_SERVER    0x00000009
#define LANG_ENGLISH                    0x09
#define SUBLANG_ARABIC_YEMEN            0x09
#define SUBLANG_ENGLISH_CARIBBEAN       0x09
#define SUBLANG_SAMI_INARI_FINLAND      0x09
#define SUBLANG_SERBIAN_SERBIA_LATIN    0x09
#define SUBLANG_SPANISH_COLOMBIA        0x09
#define ECHILD                          10
#define PRODUCT_ENTERPRISE_SERVER       0x0000000A
#define LANG_SPANISH                    0x0a
#define SUBLANG_ARABIC_SYRIA            0x0a
#define SUBLANG_ENGLISH_BELIZE          0x0a
#define SUBLANG_SERBIAN_SERBIA_CYRILLIC 0x0a
#define SUBLANG_SPANISH_PERU            0x0a
#define EAGAIN                          11
#define PRODUCT_STARTER                 0x0000000B
#define LANG_FINNISH                    0x0b
#define SUBLANG_ARABIC_JORDAN           0x0b
#define SUBLANG_ENGLISH_TRINIDAD        0x0b
#define SUBLANG_SERBIAN_MONTENEGRO_LATIN 0x0b
#define SUBLANG_SPANISH_ARGENTINA       0x0b
#define ENOMEM                          12
#define PRODUCT_DATACENTER_SERVER_CORE  0x0000000C
#define LANG_FRENCH                     0x0c
#define SUBLANG_ARABIC_LEBANON          0x0c
#define SUBLANG_ENGLISH_ZIMBABWE        0x0c
#define SUBLANG_SERBIAN_MONTENEGRO_CYRILLIC 0x0c
#define SUBLANG_SPANISH_ECUADOR         0x0c
#define EACCES                          13
#define PRODUCT_STANDARD_SERVER_CORE    0x0000000D
#define LANG_HEBREW                     0x0d
#define SUBLANG_ARABIC_KUWAIT           0x0d
#define SUBLANG_ENGLISH_PHILIPPINES     0x0d
#define SUBLANG_SPANISH_CHILE           0x0d
#define EFAULT                          14
#define PRODUCT_ENTERPRISE_SERVER_CORE  0x0000000E
#define LANG_HUNGARIAN                  0x0e
#define SUBLANG_ARABIC_UAE              0x0e
#define SUBLANG_SPANISH_URUGUAY         0x0e
#define PRODUCT_ENTERPRISE_SERVER_IA64  0x0000000F
#define LANG_ICELANDIC                  0x0f
#define SUBLANG_ARABIC_BAHRAIN          0x0f
#define SUBLANG_SPANISH_PARAGUAY        0x0f
#define _PUNCT                          0x10
#define EBUSY                           16
#define ENCLAVE_SHORT_ID_LENGTH         16
#define VER_SUITE_TERMINAL              0x00000010
#define PRODUCT_BUSINESS_N              0x00000010
#define LANG_ITALIAN                    0x10
#define SUBLANG_ARABIC_QATAR            0x10
#define SUBLANG_ENGLISH_INDIA           0x10
#define SUBLANG_SPANISH_BOLIVIA         0x10
#define EEXIST                          17
#define PRODUCT_WEB_SERVER              0x00000011
#define LANG_JAPANESE                   0x11
#define SUBLANG_ENGLISH_MALAYSIA        0x11
#define SUBLANG_SPANISH_EL_SALVADOR     0x11
#define EXDEV                           18
#define PRODUCT_CLUSTER_SERVER          0x00000012
#define LANG_KOREAN                     0x12
#define SUBLANG_ENGLISH_SINGAPORE       0x12
#define SUBLANG_SPANISH_HONDURAS        0x12
#define ENODEV                          19
#define PRODUCT_HOME_SERVER             0x00000013
#define LANG_DUTCH                      0x13
#define SUBLANG_SPANISH_NICARAGUA       0x13
#define _SAL_VERSION                    20
#define ENOTDIR                         20
#define PRODUCT_STORAGE_EXPRESS_SERVER  0x00000014
#define LANG_NORWEGIAN                  0x14
#define SUBLANG_SPANISH_PUERTO_RICO     0x14
#define EISDIR                          21
#define PRODUCT_STORAGE_STANDARD_SERVER 0x00000015
#define LANG_POLISH                     0x15
#define SUBLANG_SPANISH_US              0x15
#define PRODUCT_STORAGE_WORKGROUP_SERVER 0x00000016
#define LANG_PORTUGUESE                 0x16
#define ENFILE                          23
#define PRODUCT_STORAGE_ENTERPRISE_SERVER 0x00000017
#define LANG_ROMANSH                    0x17
#define EMFILE                          24
#define PRODUCT_SERVER_FOR_SMALLBUSINESS 0x00000018
#define LANG_ROMANIAN                   0x18
#define ENOTTY                          25
#define PRODUCT_SMALLBUSINESS_SERVER_PREMIUM 0x00000019
#define LANG_RUSSIAN                    0x19
#define PRODUCT_HOME_PREMIUM_N          0x0000001A
#define LANG_BOSNIAN                    0x1a
#define LANG_CROATIAN                   0x1a
#define LANG_SERBIAN                    0x1a
#define EFBIG                           27
#define PRODUCT_ENTERPRISE_N            0x0000001B
#define LANG_SLOVAK                     0x1b
#define ENOSPC                          28
#define PRODUCT_ULTIMATE_N              0x0000001C
#define LANG_ALBANIAN                   0x1c
#define ESPIPE                          29
#define PRODUCT_WEB_SERVER_CORE         0x0000001D
#define LANG_SWEDISH                    0x1d
#define EROFS                           30
#define PRODUCT_MEDIUMBUSINESS_SERVER_MANAGEMENT 0x0000001E
#define LANG_THAI                       0x1e
#define EMLINK                          31
#define PRODUCT_MEDIUMBUSINESS_SERVER_SECURITY 0x0000001F
#define LANG_TURKISH                    0x1f
#define _CONTROL                        0x20
#define MAXIMUM_PROC_PER_GROUP          32
#define EPIPE                           32
#define ENCLAVE_LONG_ID_LENGTH          32
#define VER_SUITE_SMALLBUSINESS_RESTRICTED 0x00000020
#define PRODUCT_MEDIUMBUSINESS_SERVER_MESSAGING 0x00000020
#define LANG_URDU                       0x20
#define EDOM                            33
#define PRODUCT_SERVER_FOUNDATION       0x00000021
#define LANG_INDONESIAN                 0x21
#define PRODUCT_HOME_PREMIUM_SERVER     0x00000022
#define LANG_UKRAINIAN                  0x22
#define PRODUCT_SERVER_FOR_SMALLBUSINESS_V 0x00000023
#define LANG_BELARUSIAN                 0x23
#define EDEADLK                         36
#define PRODUCT_STANDARD_SERVER_V       0x00000024
#define LANG_SLOVENIAN                  0x24
#define PRODUCT_DATACENTER_SERVER_V     0x00000025
#define LANG_ESTONIAN                   0x25
#define ENAMETOOLONG                    38
#define PRODUCT_ENTERPRISE_SERVER_V     0x00000026
#define LANG_LATVIAN                    0x26
#define ENOLCK                          39
#define PRODUCT_DATACENTER_SERVER_CORE_V 0x00000027
#define LANG_LITHUANIAN                 0x27
#define ENOSYS                          40
#define PRODUCT_STANDARD_SERVER_CORE_V  0x00000028
#define LANG_TAJIK                      0x28
#define ENOTEMPTY                       41
#define PRODUCT_ENTERPRISE_SERVER_CORE_V 0x00000029
#define LANG_FARSI                      0x29
#define LANG_PERSIAN                    0x29
#define PRODUCT_HYPERV                  0x0000002A
#define LANG_VIETNAMESE                 0x2a
#define PRODUCT_STORAGE_EXPRESS_SERVER_CORE 0x0000002B
#define LANG_ARMENIAN                   0x2b
#define PRODUCT_STORAGE_STANDARD_SERVER_CORE 0x0000002C
#define LANG_AZERI                      0x2c
#define LANG_AZERBAIJANI                0x2c
#define PRODUCT_STORAGE_WORKGROUP_SERVER_CORE 0x0000002D
#define LANG_BASQUE                     0x2d
#define PRODUCT_STORAGE_ENTERPRISE_SERVER_CORE 0x0000002E
#define LANG_LOWER_SORBIAN              0x2e
#define LANG_UPPER_SORBIAN              0x2e
#define PRODUCT_STARTER_N               0x0000002F
#define LANG_MACEDONIAN                 0x2f
#define PRODUCT_PROFESSIONAL            0x00000030
#define PRODUCT_PROFESSIONAL_N          0x00000031
#define PRODUCT_SB_SOLUTION_SERVER      0x00000032
#define LANG_TSWANA                     0x32
#define PRODUCT_SERVER_FOR_SB_SOLUTIONS 0x00000033
#define PRODUCT_STANDARD_SERVER_SOLUTIONS 0x00000034
#define LANG_XHOSA                      0x34
#define PRODUCT_STANDARD_SERVER_SOLUTIONS_CORE 0x00000035
#define LANG_ZULU                       0x35
#define PRODUCT_SB_SOLUTION_SERVER_EM   0x00000036
#define LANG_AFRIKAANS                  0x36
#define PRODUCT_SERVER_FOR_SB_SOLUTIONS_EM 0x00000037
#define LANG_GEORGIAN                   0x37
#define PRODUCT_SOLUTION_EMBEDDEDSERVER 0x00000038
#define LANG_FAEROESE                   0x38
#define PRODUCT_SOLUTION_EMBEDDEDSERVER_CORE 0x00000039
#define LANG_HINDI                      0x39
#define PRODUCT_PROFESSIONAL_EMBEDDED   0x0000003A
#define LANG_MALTESE                    0x3a
#define PRODUCT_ESSENTIALBUSINESS_SERVER_MGMT 0x0000003B
#define LANG_SAMI                       0x3b
#define PRODUCT_ESSENTIALBUSINESS_SERVER_ADDL 0x0000003C
#define LANG_IRISH                      0x3c
#define PRODUCT_ESSENTIALBUSINESS_SERVER_MGMTSVC 0x0000003D
#define PRODUCT_ESSENTIALBUSINESS_SERVER_ADDLSVC 0x0000003E
#define LANG_MALAY                      0x3e
#define PRODUCT_SMALLBUSINESS_SERVER_PREMIUM_CORE 0x0000003F
#define LANG_KAZAK                      0x3f
#define _BLANK                          0x40
#define VER_SUITE_EMBEDDEDNT            0x00000040
#define PRODUCT_CLUSTER_SERVER_V        0x00000040
#define LANG_KYRGYZ                     0x40
#define PRODUCT_EMBEDDED                0x00000041
#define LANG_SWAHILI                    0x41
#define PRODUCT_STARTER_E               0x00000042
#define LANG_TURKMEN                    0x42
#define PRODUCT_HOME_BASIC_E            0x00000043
#define LANG_UZBEK                      0x43
#define PRODUCT_HOME_PREMIUM_E          0x00000044
#define LANG_TATAR                      0x44
#define PRODUCT_PROFESSIONAL_E          0x00000045
#define LANG_BANGLA                     0x45
#define LANG_BENGALI                    0x45
#define PRODUCT_ENTERPRISE_E            0x00000046
#define LANG_PUNJABI                    0x46
#define PRODUCT_ULTIMATE_E              0x00000047
#define LANG_GUJARATI                   0x47
#define PRODUCT_ENTERPRISE_EVALUATION   0x00000048
#define LANG_ODIA                       0x48
#define LANG_ORIYA                      0x48
#define LANG_TAMIL                      0x49
#define LANG_TELUGU                     0x4a
#define LANG_KANNADA                    0x4b
#define PRODUCT_MULTIPOINT_STANDARD_SERVER 0x0000004C
#define LANG_MALAYALAM                  0x4c
#define PRODUCT_MULTIPOINT_PREMIUM_SERVER 0x0000004D
#define LANG_ASSAMESE                   0x4d
#define LANG_MARATHI                    0x4e
#define PRODUCT_STANDARD_EVALUATION_SERVER 0x0000004F
#define LANG_SANSKRIT                   0x4f
#define PRODUCT_DATACENTER_EVALUATION_SERVER 0x00000050
#define LANG_MONGOLIAN                  0x50
#define LANG_TIBETAN                    0x51
#define LANG_WELSH                      0x52
#define LANG_KHMER                      0x53
#define PRODUCT_ENTERPRISE_N_EVALUATION 0x00000054
#define LANG_LAO                        0x54
#define PRODUCT_EMBEDDED_AUTOMOTIVE     0x00000055
#define LOCALE_NAME_MAX_LENGTH          85
#define PRODUCT_EMBEDDED_INDUSTRY_A     0x00000056
#define LANG_GALICIAN                   0x56
#define PRODUCT_THINPC                  0x00000057
#define LANG_KONKANI                    0x57
#define PRODUCT_EMBEDDED_A              0x00000058
#define LANG_MANIPURI                   0x58
#define PRODUCT_EMBEDDED_INDUSTRY       0x00000059
#define LANG_SINDHI                     0x59
#define PRODUCT_EMBEDDED_E              0x0000005A
#define LANG_SYRIAC                     0x5a
#define PRODUCT_EMBEDDED_INDUSTRY_E     0x0000005B
#define LANG_SINHALESE                  0x5b
#define PRODUCT_EMBEDDED_INDUSTRY_A_E   0x0000005C
#define LANG_CHEROKEE                   0x5c
#define LANG_INUKTITUT                  0x5d
#define LANG_AMHARIC                    0x5e
#define PRODUCT_STORAGE_WORKGROUP_EVALUATION_SERVER 0x0000005F
#define LANG_TAMAZIGHT                  0x5f
#define PRODUCT_STORAGE_STANDARD_EVALUATION_SERVER 0x00000060
#define LANG_KASHMIRI                   0x60
#define PRODUCT_CORE_ARM                0x00000061
#define LANG_NEPALI                     0x61
#define PRODUCT_CORE_N                  0x00000062
#define LANG_FRISIAN                    0x62
#define PRODUCT_CORE_COUNTRYSPECIFIC    0x00000063
#define LANG_PASHTO                     0x63
#define WINAPI_FAMILY_DESKTOP_APP       100
#define VS_USER_DEFINED                 100
#define _ARGMAX                         100
#define EADDRINUSE                      100
#define PRODUCT_CORE_SINGLELANGUAGE     0x00000064
#define LANG_FILIPINO                   0x64
#define EADDRNOTAVAIL                   101
#define PRODUCT_CORE                    0x00000065
#define LANG_DIVEHI                     0x65
#define EAFNOSUPPORT                    102
#define EALREADY                        103
#define PRODUCT_PROFESSIONAL_WMC        0x00000067
#define LANG_FULAH                      0x67
#define LANG_PULAR                      0x67
#define EBADMSG                         104
#define LANG_HAUSA                      0x68
#define ECANCELED                       105
#define PRODUCT_EMBEDDED_INDUSTRY_EVAL  0x00000069
#define ECONNABORTED                    106
#define PRODUCT_EMBEDDED_INDUSTRY_E_EVAL 0x0000006A
#define LANG_YORUBA                     0x6a
#define ECONNREFUSED                    107
#define PRODUCT_EMBEDDED_EVAL           0x0000006B
#define LANG_QUECHUA                    0x6b
#define ECONNRESET                      108
#define PRODUCT_EMBEDDED_E_EVAL         0x0000006C
#define LANG_SOTHO                      0x6c
#define EDESTADDRREQ                    109
#define PRODUCT_NANO_SERVER             0x0000006D
#define LANG_BASHKIR                    0x6d
#define EHOSTUNREACH                    110
#define PRODUCT_CLOUD_STORAGE_SERVER    0x0000006E
#define LANG_LUXEMBOURGISH              0x6e
#define EIDRM                           111
#define PRODUCT_CORE_CONNECTED          0x0000006F
#define LANG_GREENLANDIC                0x6f
#define EINPROGRESS                     112
#define PRODUCT_PROFESSIONAL_STUDENT    0x00000070
#define LANG_IGBO                       0x70
#define EISCONN                         113
#define PRODUCT_CORE_CONNECTED_N        0x00000071
#define ELOOP                           114
#define PRODUCT_PROFESSIONAL_STUDENT_N  0x00000072
#define EMSGSIZE                        115
#define PRODUCT_CORE_CONNECTED_SINGLELANGUAGE 0x00000073
#define LANG_TIGRIGNA                   0x73
#define LANG_TIGRINYA                   0x73
#define ENETDOWN                        116
#define PRODUCT_CORE_CONNECTED_COUNTRYSPECIFIC 0x00000074
#define ENETRESET                       117
#define PRODUCT_CONNECTED_CAR           0x00000075
#define LANG_HAWAIIAN                   0x75
#define ENETUNREACH                     118
#define PRODUCT_INDUSTRY_HANDHELD       0x00000076
#define ENOBUFS                         119
#define PRODUCT_PPI_PRO                 0x00000077
#define ENODATA                         120
#define PRODUCT_ARM64_SERVER            0x00000078
#define LANG_YI                         0x78
#define ENOLINK                         121
#define PRODUCT_EDUCATION               0x00000079
#define ENOMSG                          122
#define PRODUCT_EDUCATION_N             0x0000007A
#define LANG_MAPUDUNGUN                 0x7a
#define ENOPROTOOPT                     123
#define PRODUCT_IOTUAP                  0x0000007B
#define ENOSR                           124
#define PRODUCT_CLOUD_HOST_INFRASTRUCTURE_SERVER 0x0000007C
#define LANG_MOHAWK                     0x7c
#define ENOSTR                          125
#define PRODUCT_ENTERPRISE_S            0x0000007D
#define ENOTCONN                        126
#define PRODUCT_ENTERPRISE_S_N          0x0000007E
#define LANG_BRETON                     0x7e
#define ENOTRECOVERABLE                 127
#define MAXCHAR                         0x7f
#define PRODUCT_PROFESSIONAL_S          0x0000007F
#define LANG_INVARIANT                  0x7f
#define _HEX                            0x80
#define SYSTEM_CACHE_ALIGNMENT_SIZE     128
#define ENOTSOCK                        128
#define MINCHAR                         0x80
#define VER_SUITE_DATACENTER            0x00000080
#define PRODUCT_PROFESSIONAL_S_N        0x00000080
#define LANG_UIGHUR                     0x80
#define ENOTSUP                         129
#define PRODUCT_ENTERPRISE_S_EVALUATION 0x00000081
#define LANG_MAORI                      0x81
#define EOPNOTSUPP                      130
#define PRODUCT_ENTERPRISE_S_N_EVALUATION 0x00000082
#define LANG_OCCITAN                    0x82
#define EOTHER                          131
#define LANG_CORSICAN                   0x83
#define EOVERFLOW                       132
#define LANG_ALSATIAN                   0x84
#define EOWNERDEAD                      133
#define LANG_SAKHA                      0x85
#define LANG_YAKUT                      0x85
#define EPROTO                          134
#define LANG_KICHE                      0x86
#define EPROTONOSUPPORT                 135
#define PRODUCT_HOLOGRAPHIC             0x00000087
#define LANG_KINYARWANDA                0x87
#define EPROTOTYPE                      136
#define PRODUCT_HOLOGRAPHIC_BUSINESS    0x00000088
#define LANG_WOLOF                      0x88
#define ETIME                           137
#define ETIMEDOUT                       138
#define PRODUCT_PRO_SINGLE_LANGUAGE     0x0000008A
#define ETXTBSY                         139
#define PRODUCT_PRO_CHINA               0x0000008B
#define EWOULDBLOCK                     140
#define PRODUCT_ENTERPRISE_SUBSCRIPTION 0x0000008C
#define LANG_DARI                       0x8c
#define PRODUCT_ENTERPRISE_SUBSCRIPTION_N 0x0000008D
#define PRODUCT_DATACENTER_NANO_SERVER  0x0000008F
#define PRODUCT_STANDARD_NANO_SERVER    0x00000090
#define PRODUCT_DATACENTER_A_SERVER_CORE 0x00000091
#define LANG_SCOTTISH_GAELIC            0x91
#define PRODUCT_STANDARD_A_SERVER_CORE  0x00000092
#define LANG_CENTRAL_KURDISH            0x92
#define PRODUCT_DATACENTER_WS_SERVER_CORE 0x00000093
#define PRODUCT_STANDARD_WS_SERVER_CORE 0x00000094
#define PRODUCT_UTILITY_VM              0x00000095
#define PRODUCT_DATACENTER_EVALUATION_SERVER_CORE 0x0000009F
#define PRODUCT_STANDARD_EVALUATION_SERVER_CORE 0x000000A0
#define PRODUCT_PRO_WORKSTATION         0x000000A1
#define PRODUCT_PRO_WORKSTATION_N       0x000000A2
#define PRODUCT_PRO_FOR_EDUCATION       0x000000A4
#define PRODUCT_PRO_FOR_EDUCATION_N     0x000000A5
#define PRODUCT_AZURE_SERVER_CORE       0x000000A8
#define PRODUCT_AZURE_NANO_SERVER       0x000000A9
#define PRODUCT_ENTERPRISEG             0x000000AB
#define PRODUCT_ENTERPRISEGN            0x000000AC
#define PRODUCT_SERVERRDSH              0x000000AF
#define PRODUCT_CLOUD                   0x000000B2
#define PRODUCT_CLOUDN                  0x000000B3
#define PRODUCT_HUBOS                   0x000000B4
#define PRODUCT_ONECOREUPDATEOS         0x000000B6
#define PRODUCT_CLOUDE                  0x000000B7
#define PRODUCT_ANDROMEDA               0x000000B8
#define PRODUCT_IOTOS                   0x000000B9
#define PRODUCT_CLOUDEN                 0x000000BA
#define PRODUCT_IOTEDGEOS               0x000000BB
#define PRODUCT_IOTENTERPRISE           0x000000BC
#define PRODUCT_LITE                    0x000000BD
#define PRODUCT_IOTENTERPRISES          0x000000BF
#define _SECURECRT_FILL_BUFFER_PATTERN  0xFE
#define MAXUCHAR                        0xff
#define SUBVERSION_MASK                 0x000000FF
#define VER_SUITE_SINGLEUSERTS          0x00000100
#define VER_SUITE_PERSONAL              0x00000200
#define _WIN32_IE_IE20                  0x0200
#define _WIN32_IE_IE30                  0x0300
#define _WIN32_IE_IE302                 0x0302
#define VER_SUITE_BLADE                 0x00000400
#define _WIN32_WINNT_NT4                0x0400
#define _WIN32_IE_IE40                  0x0400
#define _WIN32_IE_IE401                 0x0401
#define _WIN32_WINNT_WIN2K              0x0500
#define _WIN32_IE_IE50                  0x0500
#define _WIN32_WINNT_WINXP              0x0501
#define _WIN32_IE_IE501                 0x0501
#define _WIN32_WINNT_WS03               0x0502
#define _WIN32_IE_IE55                  0x0550
#define _WIN32_WINNT_WIN6               0x0600
#define _WIN32_WINNT_VISTA              0x0600
#define _WIN32_WINNT_WS08               0x0600
#define _WIN32_WINNT_LONGHORN           0x0600
#define _WIN32_IE_IE60                  0x0600
#define _WIN32_WINNT_WIN7               0x0601
#define _WIN32_IE_IE60SP1               0x0601
#define _WIN32_WINNT_WIN8               0x0602
#define _WIN32_IE_WS03                  0x0602
#define _WIN32_WINNT_WINBLUE            0x0603
#define _WIN32_IE_IE60SP2               0x0603
#define _WIN32_IE_IE70                  0x0700
#define VER_SUITE_EMBEDDED_RESTRICTED   0x00000800
#define _WIN32_IE_IE80                  0x0800
#define _WIN32_IE_IE90                  0x0900
#define _WIN32_WINNT_WINTHRESHOLD       0x0A00
#define _WIN32_WINNT_WIN10              0x0A00
#define _WIN32_IE_IE100                 0x0A00
#define _WIN32_IE_IE110                 0x0A00
#define _WIN32_WINNT                    0x0A00
#define _WIN32_IE                       0x0A00
#define VER_SUITE_SECURITY_APPLIANCE    0x00001000
#define VER_SUITE_STORAGE_SERVER        0x00002000
#define LOCALE_TRANSIENT_KEYBOARD1      0x2000
#define LOCALE_TRANSIENT_KEYBOARD2      0x2400
#define LOCALE_TRANSIENT_KEYBOARD3      0x2800
#define LOCALE_TRANSIENT_KEYBOARD4      0x2c00
#define VER_SUITE_COMPUTE_SERVER        0x00004000
#define LANG_BOSNIAN_NEUTRAL            0x781a
#define LANG_CHINESE_TRADITIONAL        0x7c04
#define LANG_SERBIAN_NEUTRAL            0x7c1a
#define MAXSHORT                        0x7fff
#define _LEADBYTE                       0x8000
#define MINSHORT                        0x8000
#define VER_SUITE_WH_SERVER             0x00008000
#define SPVERSION_MASK                  0x0000FF00
#define ALL_PROCESSOR_GROUPS            0xffff
#define MAXUSHORT                       0xffff
#define EXCEPTION_CONTINUE_EXECUTION    -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
